### ISSUE TITLE
getData doesn't indicate bad data, as suggested

### ISSUE THREAD

**Issue by berrydan** [leleopard/pyXPUDPServer#1]
"The method will automatically request XP to send the dataref if it has not been done previously. :return: value of the dataref (float) or 0.0 by default if no data Received"

While this appears to be true on the first getData read of a new dataref, it doesn't appear to be true for subsequent getData requests. If XP crashes (for example), it's reasonable to expect it to return "0.0", but instead it returns the last read value.

Similarly, there exists the "XPalive" property, but this appears to constantly return False...

**Comment by leleopard** [comment]
appreciating this is a very late response. The getData method was designed to return the latest value received from xplane, or 0.0 by default if no data received, the documentation was updated to reflect this probably after this comment. The behaviour could be changed if needed. 
I would suggest re testing the XPalive behaviour on the latest version as it worked for me on XP11, although admittedly I haven't run this library with the latest version of Xplane for a while
