### ISSUE TITLE
can't reconnect after calling quit()

### ISSUE THREAD

**Issue by ghost** [leleopard/pyXPUDPServer#3]
Unable to call start() after calling quit(). RuntimeError is raised "threads can only be started once".

**Comment by leleopard** [comment]
sorry for a very late response. python only allows a thread to be started once. The way I designed this class is that it is started and keeps running in the background of your main programme, you would only call quit() once you decide to close your main programme. What use case are you trying to achieve? The class should keep track of your xplane instance and automatically reconnect if say xplane crashes and you then re launch it.
